-- =============================================================================
-- schema.sql — all migrations concatenated, in order.
--
-- GENERATED by `npm run schema`. Edit the files in supabase/migrations/,
-- not this file.
--
-- Paste into the Supabase SQL editor and run once, on an empty project. The
-- final block stamps schema_migrations so a later `npm run migrate` skips them.
-- =============================================================================

-- >>>>>>>>>>>>>>>>>>>> 20260827000001_core_schema.sql <<<<<<<<<<<<<<<<<<<<
-- =============================================================================
-- 0001_core_schema.sql — reference, source-mirror and canonical layers
--
-- Layer 1 (reference)     brands, countries, sites, players, technologies
-- Layer 2 (source mirror) categories, products, variants, product_categories,
--                         product_content  — what the site literally says
-- Layer 3 (canonical)     product_lines, generations, models — what we derive
--
-- The split exists because storefronts model the same physical hierarchy
-- inconsistently. See docs/DESIGN.md §5.
-- =============================================================================

create extension if not exists "pgcrypto";     -- gen_random_uuid()
create extension if not exists "pg_trgm";      -- fuzzy name matching in normalize

-- =============================================================================
-- Enumerated domains. Kept as CHECK constraints rather than PG enums so that
-- adding a value is a migration, not an ALTER TYPE that locks readers.
-- =============================================================================

-- skill_tier      pro | performance | recreational | premium | junior | unknown
-- paddle_shape    elongated | hybrid | standard | widebody | unknown
-- attr_source     source_option | title | tag | collection | pdp | llm | manual
-- category_role   sport | assortment | skill_tier | generation | series
--                 | signature | sale | accessory | other

-- =============================================================================
-- Layer 1 — reference
-- =============================================================================

create table brands (
  id            uuid primary key default gen_random_uuid(),
  slug          text not null unique,               -- 'joola'
  name          text not null,                      -- 'JOOLA'
  created_at    timestamptz not null default now()
);

create table countries (
  code          text primary key,                   -- ISO-3166-1 alpha-2, 'US'
  name          text not null,
  currency      text not null                       -- ISO-4217 default, 'USD'
);

-- One row per (brand, country) storefront. This is the crawl target and the
-- unit that country expansion adds rows to.
create table sites (
  id                uuid primary key default gen_random_uuid(),
  brand_id          uuid not null references brands(id) on delete cascade,
  country_code      text not null references countries(code),
  base_url          text not null,                  -- 'https://joola.com'
  platform          text not null,                  -- 'shopify' | 'woocommerce' | 'custom'
  currency          text not null,
  locale            text not null default 'en-US',
  -- Which source collections make up the assortment we care about. Declared in
  -- config and mirrored here so a query can explain why a product was crawled.
  assortment_handles text[] not null default '{}',
  is_active         boolean not null default true,
  crawl_delay_ms    integer not null default 1200,  -- politeness; robots may raise it
  notes             text,
  created_at        timestamptz not null default now(),
  unique (brand_id, country_code, base_url)
);

-- Endorsing athletes. Colourways on this brand are named after players
-- ('Blaze Red (Ben Johns)'), which makes the player a real analytic dimension.
create table players (
  id            uuid primary key default gen_random_uuid(),
  brand_id      uuid references brands(id) on delete cascade,
  name          text not null,
  slug          text not null,
  created_at    timestamptz not null default now(),
  unique (brand_id, slug)
);

-- Brand technology dictionary ('Carbon Friction Surface', 'Propulsion Core').
create table technologies (
  id            uuid primary key default gen_random_uuid(),
  brand_id      uuid not null references brands(id) on delete cascade,
  name          text not null,
  slug          text not null,
  description   text,
  first_seen_at timestamptz not null default now(),
  unique (brand_id, slug)
);

-- =============================================================================
-- Layer 3 — canonical hierarchy (declared before layer 2 so products can FK to it)
--
--   product_line  Perseus
--   generation    Pro V
--   model         Perseus Pro V   (line × generation × optional sub-line 'Dual')
-- =============================================================================

create table product_lines (
  id            uuid primary key default gen_random_uuid(),
  brand_id      uuid not null references brands(id) on delete cascade,
  slug          text not null,                      -- 'perseus'
  name          text not null,                      -- 'Perseus'
  description   text,
  created_at    timestamptz not null default now(),
  unique (brand_id, slug)
);

create table generations (
  id            uuid primary key default gen_random_uuid(),
  brand_id      uuid not null references brands(id) on delete cascade,
  slug          text not null,                      -- 'pro-v'
  name          text not null,                      -- 'Pro V'
  -- Ordering for "which version is newer". Gen 1 = 1, Pro IV = 4, Pro V = 5.
  sequence      integer,
  released_at   date,
  created_at    timestamptz not null default now(),
  unique (brand_id, slug)
);

create table models (
  id                uuid primary key default gen_random_uuid(),
  brand_id          uuid not null references brands(id) on delete cascade,
  product_line_id   uuid references product_lines(id) on delete set null,
  generation_id     uuid references generations(id) on delete set null,
  sub_line          text,                           -- 'Dual', 'CFS', NULL
  slug              text not null,                  -- 'perseus-pro-v'
  name              text not null,                  -- 'Perseus Pro V'
  skill_tier        text not null default 'unknown'
                    check (skill_tier in ('pro','performance','recreational',
                                          'premium','junior','unknown')),
  shape             text not null default 'unknown'
                    check (shape in ('elongated','hybrid','standard',
                                     'widebody','unknown')),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (brand_id, slug)
);

create index models_line_idx on models(product_line_id);
create index models_generation_idx on models(generation_id);
create index models_skill_tier_idx on models(skill_tier);

-- =============================================================================
-- Layer 2 — source mirror
-- =============================================================================

-- Collections / menu nodes as published by the site. Self-referencing so the
-- mega-menu tree survives intact; `nav_path` carries the human breadcrumb.
create table categories (
  id                  uuid primary key default gen_random_uuid(),
  site_id             uuid not null references sites(id) on delete cascade,
  source_category_id  text not null,                -- Shopify collection id
  handle              text not null,                -- 'professional-pickleball-paddles'
  title               text not null,                -- 'Pro'
  description         text,
  url                 text,
  parent_id           uuid references categories(id) on delete set null,
  depth               integer not null default 0,
  nav_path            text[] not null default '{}', -- {'Pickleball','Paddles','Pro'}
  -- Derived: what this collection *means*. Drives the UI's facet grouping.
  category_role       text not null default 'other'
                      check (category_role in ('sport','assortment','skill_tier',
                             'generation','series','signature','sale','accessory','other')),
  position            integer,
  in_main_nav         boolean not null default false,
  product_count       integer not null default 0,
  first_seen_at       timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  is_active           boolean not null default true,
  unique (site_id, source_category_id)
);

create index categories_site_role_idx on categories(site_id, category_role);
create index categories_handle_idx on categories(site_id, handle);

-- One row per product per site. The same physical paddle sold in the US and in
-- Australia is two rows; that is intentional.
create table products (
  id                  uuid primary key default gen_random_uuid(),
  site_id             uuid not null references sites(id) on delete cascade,
  model_id            uuid references models(id) on delete set null,  -- resolved in normalize
  source_product_id   text not null,
  handle              text not null,
  title               text not null,
  vendor              text,
  product_type        text,
  tags                text[] not null default '{}',
  body_html           text,
  url                 text,
  image_url           text,
  published_at        timestamptz,
  source_created_at   timestamptz,
  source_updated_at   timestamptz,
  -- Assortment gate. Accessories and apparel slip into collections; this is the
  -- flag every analytic query filters on.
  is_in_assortment    boolean not null default true,
  first_seen_at       timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  is_active           boolean not null default true,
  unique (site_id, source_product_id)
);

create index products_site_idx on products(site_id);
create index products_model_idx on products(model_id);
create index products_handle_idx on products(site_id, handle);
create index products_tags_idx on products using gin(tags);
create index products_title_trgm_idx on products using gin(title gin_trgm_ops);

-- Membership changes over time — a product entering the 'Sale' collection is a
-- signal in its own right, so this carries first/last seen rather than being a
-- plain join table.
create table product_categories (
  product_id      uuid not null references products(id) on delete cascade,
  category_id     uuid not null references categories(id) on delete cascade,
  position        integer,
  first_seen_at   timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  is_active       boolean not null default true,
  primary key (product_id, category_id)
);

create index product_categories_category_idx on product_categories(category_id);

-- The SKU. Atomic unit of price/stock time series.
create table variants (
  id                  uuid primary key default gen_random_uuid(),
  product_id          uuid not null references products(id) on delete cascade,
  site_id             uuid not null references sites(id) on delete cascade,
  source_variant_id   text not null,
  sku                 text,
  barcode             text,
  title               text,                         -- '16mm / Blaze Red (Ben Johns)'
  position            integer,
  image_url           text,

  -- Raw option values exactly as the source gave them, so a normalization bug
  -- is always recoverable without a re-crawl.
  option1_name        text,
  option1_value       text,
  option2_name        text,
  option2_value       text,
  option3_name        text,
  option3_value       text,

  -- ---- derived attributes (normalize stage) --------------------------------
  -- These are the answer to "what sizes / colours / versions exist". They are
  -- populated from option values, product title, tags, collections or the PDP,
  -- whichever wins; attr_source records which, per docs/DESIGN.md §3.
  core_thickness_mm   numeric(4,1),                 -- 14.0 | 16.0
  colorway            text,                         -- 'Blaze Red'
  color_primary       text,
  color_secondary     text,
  endorsed_player_id  uuid references players(id) on delete set null,
  weight_grams        numeric(6,2),
  grip_length_mm      numeric(5,1),
  paddle_length_mm    numeric(5,1),
  paddle_width_mm     numeric(5,1),
  shape               text check (shape in ('elongated','hybrid','standard',
                                            'widebody','unknown')),
  attr_source         jsonb not null default '{}'::jsonb,  -- {"core_thickness_mm":"title"}
  attr_confidence     numeric(3,2),                 -- 0.00–1.00, lowest across attrs

  -- Long-tail specs that do not deserve a column.
  attributes          jsonb not null default '{}'::jsonb,

  first_seen_at       timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  is_active           boolean not null default true,
  unique (site_id, source_variant_id)
);

create index variants_product_idx on variants(product_id);
create index variants_site_idx on variants(site_id);
create index variants_sku_idx on variants(sku);
create index variants_thickness_idx on variants(core_thickness_mm);
create index variants_player_idx on variants(endorsed_player_id);

-- PDP-derived content. Versioned by content_hash so re-crawls that changed
-- nothing do not create rows, but a genuine copy/spec change is preserved.
create table product_content (
  id              uuid primary key default gen_random_uuid(),
  product_id      uuid not null references products(id) on delete cascade,
  content_hash    varchar(64) not null,             -- sha256 of the normalised payload
  description     text,
  specs           jsonb not null default '{}'::jsonb,   -- {'Core':'16mm Polypropylene'}
  technologies    text[] not null default '{}',
  media           jsonb not null default '[]'::jsonb,
  breadcrumb      text[] not null default '{}',
  captured_at     timestamptz not null default now(),
  unique (product_id, content_hash)
);

create index product_content_product_idx on product_content(product_id, captured_at desc);

create table product_technologies (
  product_id      uuid not null references products(id) on delete cascade,
  technology_id   uuid not null references technologies(id) on delete cascade,
  primary key (product_id, technology_id)
);

-- =============================================================================
-- updated_at maintenance
-- =============================================================================

create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger models_touch before update on models
  for each row execute function touch_updated_at();

-- >>>>>>>>>>>>>>>>>>>> 20260827000002_timeseries.sql <<<<<<<<<<<<<<<<<<<<
-- =============================================================================
-- 0002_timeseries.sql — crawl runs and the price / discount / stock history
--
-- This is the reason the project exists. A catalogue scrape tells you what is
-- sold today; these tables tell you what changed and when.
--
-- Sizing: 116 variants/day for JOOLA US is ~42k snapshot rows/year. At 20
-- brands x 4 countries x 500 variants it is ~15M/year — the point at which
-- monthly partitioning of variant_snapshots becomes worthwhile. See §"scaling"
-- at the bottom.
-- =============================================================================

-- One row per crawl. Everything written by a run carries its run_id so a bad
-- run can be identified, explained, and excluded from charts.
create table crawl_runs (
  id                uuid primary key default gen_random_uuid(),
  site_id           uuid not null references sites(id) on delete cascade,
  run_type          text not null default 'scheduled'
                    check (run_type in ('scheduled','manual','backfill')),
  status            text not null default 'pending'
                    check (status in ('pending','running','done','partial','error')),
  -- Which stages were requested vs completed, for the pipeline-health panel.
  stages_requested  text[] not null default '{}',
  stages_done       text[] not null default '{}',
  categories_found  integer not null default 0,
  products_found    integer not null default 0,
  products_new      integer not null default 0,
  variants_found    integer not null default 0,
  variants_new      integer not null default 0,
  snapshots_written integer not null default 0,
  events_written    integer not null default 0,
  stats             jsonb not null default '{}'::jsonb,
  error_message     text,
  started_at        timestamptz not null default now(),
  finished_at       timestamptz,
  created_at        timestamptz not null default now()
);

create index crawl_runs_site_started_idx on crawl_runs(site_id, started_at desc);
create index crawl_runs_status_idx on crawl_runs(status);

create table crawl_errors (
  id              uuid primary key default gen_random_uuid(),
  run_id          uuid not null references crawl_runs(id) on delete cascade,
  stage           text not null,
  target          text,                              -- the URL/handle that failed
  error_type      text not null default 'stage_error'
                  check (error_type in ('http_error','parse_error','timeout',
                                        'stage_error','normalize_error','db_error')),
  error_message   text,
  status_code     integer,
  created_at      timestamptz not null default now()
);

create index crawl_errors_run_idx on crawl_errors(run_id);

-- =============================================================================
-- variant_snapshots — append-only. One row per variant per successful run.
--
-- observed_at is when WE LOOKED, not when the price changed. Charts must step-
-- interpolate between points, never linearly interpolate.
--
-- A failed run writes NO snapshots, so a site outage can never be mistaken for
-- a catalogue-wide stockout.
-- =============================================================================
create table variant_snapshots (
  id                  bigserial primary key,
  run_id              uuid not null references crawl_runs(id) on delete cascade,
  variant_id          uuid not null references variants(id) on delete cascade,
  site_id             uuid not null references sites(id) on delete cascade,
  observed_at         timestamptz not null default now(),

  price               numeric(12,2),
  compare_at_price    numeric(12,2),
  currency            text not null,

  -- Stored generated columns: "everything over 20% off on any past date"
  -- becomes an index scan instead of a scan-plus-arithmetic.
  is_on_sale          boolean generated always as (
                        compare_at_price is not null
                        and price is not null
                        and compare_at_price > price
                      ) stored,
  discount_pct        numeric(5,2) generated always as (
                        case
                          when compare_at_price is not null
                           and price is not null
                           and compare_at_price > 0
                           and compare_at_price > price
                          then round(((compare_at_price - price) / compare_at_price) * 100, 2)
                          else 0
                        end
                      ) stored,

  is_available        boolean,
  inventory_quantity  integer,                       -- null when not exposed
  -- Merchandising position within its primary collection. Movement here is an
  -- early signal of a push or a wind-down.
  position_in_category integer,

  -- Guards against double-writing a variant within one run.
  unique (run_id, variant_id)
);

create index variant_snapshots_variant_time_idx
  on variant_snapshots(variant_id, observed_at desc);
create index variant_snapshots_site_time_idx
  on variant_snapshots(site_id, observed_at desc);
-- BRIN is the right index for an append-only, time-ordered column: tiny, and
-- effective for the range scans that every trend chart issues.
create index variant_snapshots_observed_brin_idx
  on variant_snapshots using brin(observed_at);
create index variant_snapshots_on_sale_idx
  on variant_snapshots(observed_at desc) where is_on_sale;

-- =============================================================================
-- variant_events — the derived change-log.
--
-- Written by the diff stage by comparing a run against the previous successful
-- run. Everything here is recomputable from variant_snapshots; it exists so the
-- dashboard and any alerting can answer "what changed" without window functions
-- over the full history.
-- =============================================================================
create table variant_events (
  id              bigserial primary key,
  run_id          uuid not null references crawl_runs(id) on delete cascade,
  variant_id      uuid not null references variants(id) on delete cascade,
  site_id         uuid not null references sites(id) on delete cascade,
  event_type      text not null check (event_type in (
                    'listed','delisted',
                    'price_increase','price_decrease',
                    'discount_started','discount_deepened','discount_ended',
                    'went_oos','back_in_stock',
                    'category_added','category_removed'
                  )),
  occurred_at     timestamptz not null default now(),
  old_value       text,
  new_value       text,
  delta_numeric   numeric(12,2),                     -- signed price delta where relevant
  delta_pct       numeric(6,2),
  context         jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now()
);

create index variant_events_variant_time_idx on variant_events(variant_id, occurred_at desc);
create index variant_events_site_time_idx on variant_events(site_id, occurred_at desc);
create index variant_events_type_time_idx on variant_events(event_type, occurred_at desc);

-- =============================================================================
-- Scaling note (deliberately not implemented yet — YAGNI)
--
-- At roughly 10M rows, convert variant_snapshots to a monthly-partitioned table:
--
--   create table variant_snapshots (...) partition by range (observed_at);
--   create table variant_snapshots_2026_08
--     partition of variant_snapshots
--     for values from ('2026-08-01') to ('2026-09-01');
--
-- Nothing in the application reads variant_snapshots directly except the
-- pipeline and the views in 0003, so this stays a contained change.
-- =============================================================================

-- >>>>>>>>>>>>>>>>>>>> 20260827000003_views.sql <<<<<<<<<<<<<<<<<<<<
-- =============================================================================
-- 0003_views.sql — the read surface.
--
-- The frontend should query these, never the raw tables. That keeps the
-- "never linearly interpolate", "always filter is_in_assortment" and "latest
-- snapshot per variant" rules in one place instead of in every component.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Current state of every SKU: newest snapshot, joined through to the canonical
-- model. This is the workhorse for catalogue browsing.
-- -----------------------------------------------------------------------------
create or replace view v_variant_current as
select
  v.id                    as variant_id,
  v.sku,
  v.title                 as variant_title,
  v.core_thickness_mm,
  v.colorway,
  v.shape                 as variant_shape,
  v.attr_confidence,
  pl_player.name          as endorsed_player,

  p.id                    as product_id,
  p.title                 as product_title,
  p.handle,
  p.url                   as product_url,
  p.image_url,
  p.tags,
  p.is_in_assortment,

  m.id                    as model_id,
  m.name                  as model_name,
  m.skill_tier,
  m.shape                 as model_shape,
  line.name               as product_line,
  gen.name                as generation,
  gen.sequence            as generation_sequence,

  s.id                    as site_id,
  b.name                  as brand,
  s.country_code,

  snap.observed_at,
  snap.price,
  snap.compare_at_price,
  snap.currency,
  snap.is_on_sale,
  snap.discount_pct,
  snap.is_available,
  snap.inventory_quantity,

  v.is_active
from variants v
join products p        on p.id = v.product_id
join sites s           on s.id = v.site_id
join brands b          on b.id = s.brand_id
left join models m     on m.id = p.model_id
left join product_lines line on line.id = m.product_line_id
left join generations gen    on gen.id = m.generation_id
left join players pl_player  on pl_player.id = v.endorsed_player_id
-- Newest snapshot per variant. LATERAL keeps this an index seek per variant
-- rather than a sort over the whole history.
left join lateral (
  select vs.observed_at, vs.price, vs.compare_at_price, vs.currency,
         vs.is_on_sale, vs.discount_pct, vs.is_available, vs.inventory_quantity
  from variant_snapshots vs
  where vs.variant_id = v.id
  order by vs.observed_at desc
  limit 1
) snap on true;

-- -----------------------------------------------------------------------------
-- The direct answer to the brief: for each model, how many versions, which
-- thicknesses, which colourways, what price band.
-- -----------------------------------------------------------------------------
create or replace view v_model_overview as
select
  m.id                as model_id,
  b.name              as brand,
  line.name           as product_line,
  gen.name            as generation,
  gen.sequence        as generation_sequence,
  m.name              as model_name,
  m.skill_tier,
  m.shape,
  count(distinct vc.variant_id)                              as sku_count,
  array_agg(distinct vc.core_thickness_mm)
    filter (where vc.core_thickness_mm is not null)          as thicknesses_mm,
  array_agg(distinct vc.colorway)
    filter (where vc.colorway is not null)                   as colorways,
  array_agg(distinct vc.endorsed_player)
    filter (where vc.endorsed_player is not null)            as endorsed_players,
  min(vc.price)                                              as price_min,
  max(vc.price)                                              as price_max,
  count(*) filter (where vc.is_available)                    as skus_in_stock,
  count(*) filter (where vc.is_on_sale)                      as skus_on_sale,
  max(vc.discount_pct)                                       as best_discount_pct,
  vc.currency,
  vc.country_code
from models m
join brands b on b.id = m.brand_id
left join product_lines line on line.id = m.product_line_id
left join generations gen    on gen.id = m.generation_id
join v_variant_current vc    on vc.model_id = m.id
where vc.is_in_assortment
group by m.id, b.name, line.name, gen.name, gen.sequence,
         m.name, m.skill_tier, m.shape, vc.currency, vc.country_code;

-- -----------------------------------------------------------------------------
-- Daily price series. One row per variant per day; where a day has several
-- observations, the last one wins as the close and min/max show the intraday
-- band. Days with no crawl are simply absent — the caller must step-fill, not
-- interpolate (docs/DESIGN.md §6).
-- -----------------------------------------------------------------------------
create or replace view v_variant_price_daily as
select
  vs.variant_id,
  vs.site_id,
  (vs.observed_at at time zone 'UTC')::date          as day,
  min(vs.price)                                      as price_min,
  max(vs.price)                                      as price_max,
  (array_agg(vs.price order by vs.observed_at desc))[1]            as price_close,
  (array_agg(vs.compare_at_price order by vs.observed_at desc))[1] as compare_at_close,
  (array_agg(vs.discount_pct order by vs.observed_at desc))[1]     as discount_pct_close,
  bool_or(vs.is_on_sale)                             as was_on_sale,
  bool_or(vs.is_available)                           as was_available,
  bool_and(vs.is_available)                          as was_always_available,
  count(*)                                           as observations,
  max(vs.currency)                                   as currency
from variant_snapshots vs
group by vs.variant_id, vs.site_id, (vs.observed_at at time zone 'UTC')::date;

-- -----------------------------------------------------------------------------
-- Everything currently discounted, deepest first.
-- -----------------------------------------------------------------------------
create or replace view v_active_discounts as
select
  vc.brand, vc.country_code, vc.product_line, vc.generation, vc.model_name,
  vc.product_title, vc.variant_title, vc.sku, vc.core_thickness_mm, vc.colorway,
  vc.price, vc.compare_at_price, vc.discount_pct, vc.currency,
  vc.is_available, vc.product_url, vc.observed_at
from v_variant_current vc
where vc.is_on_sale and vc.is_in_assortment
order by vc.discount_pct desc;

-- -----------------------------------------------------------------------------
-- Site taxonomy as a breadcrumb list — the captured menu structure.
-- -----------------------------------------------------------------------------
create or replace view v_category_tree as
select
  c.id as category_id, c.site_id, b.name as brand, s.country_code,
  c.handle, c.title, c.category_role, c.depth, c.nav_path, c.in_main_nav,
  c.parent_id, parent.title as parent_title,
  count(pc.product_id) filter (where pc.is_active) as active_products,
  c.is_active
from categories c
join sites s  on s.id = c.site_id
join brands b on b.id = s.brand_id
left join categories parent on parent.id = c.parent_id
left join product_categories pc on pc.category_id = c.id
group by c.id, b.name, s.country_code, parent.title;

-- -----------------------------------------------------------------------------
-- Recent changes feed — what moved, newest first.
-- -----------------------------------------------------------------------------
create or replace view v_recent_changes as
select
  e.id, e.event_type, e.occurred_at, e.old_value, e.new_value,
  e.delta_numeric, e.delta_pct,
  v.sku, v.title as variant_title, v.core_thickness_mm, v.colorway,
  p.title as product_title, p.url as product_url,
  m.name as model_name, m.skill_tier,
  b.name as brand, s.country_code
from variant_events e
join variants v on v.id = e.variant_id
join products p on p.id = v.product_id
join sites s    on s.id = e.site_id
join brands b   on b.id = s.brand_id
left join models m on m.id = p.model_id
order by e.occurred_at desc;

-- >>>>>>>>>>>>>>>>>>>> 20260827000004_rls_and_seed.sql <<<<<<<<<<<<<<<<<<<<
-- =============================================================================
-- 0004_rls_and_seed.sql — access control, then the JOOLA US seed.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- RLS. The ingest runs with the service_role key, which bypasses RLS entirely.
-- Everything else is denied unless a policy grants it. Enabling RLS without
-- adding a permissive policy is the deny-by-default posture we want here: the
-- anon key is safe to ship to a browser because it can read nothing.
--
-- When the dashboard needs direct browser reads, add read-only policies for the
-- `authenticated` role. Until then, the Next.js app should read through a
-- server-side route using the service key.
-- -----------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'brands','countries','sites','players','technologies',
    'product_lines','generations','models',
    'categories','products','variants','product_categories',
    'product_content','product_technologies',
    'crawl_runs','crawl_errors','variant_snapshots','variant_events'
  ] loop
    execute format('alter table %I enable row level security', t);
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- Seed: countries
-- -----------------------------------------------------------------------------
insert into countries (code, name, currency) values
  ('US', 'United States', 'USD'),
  ('IN', 'India',         'INR'),
  ('AU', 'Australia',     'AUD'),
  ('VN', 'Vietnam',       'VND')
on conflict (code) do nothing;

-- -----------------------------------------------------------------------------
-- Seed: JOOLA + its US storefront
--
-- assortment_handles are the collections verified to exist on joola.com and to
-- contain paddles. 'pickleball-paddles' is the parent; the rest are the skill
-- tiers, generations and series that give the taxonomy its shape.
-- -----------------------------------------------------------------------------
insert into brands (slug, name) values ('joola', 'JOOLA')
on conflict (slug) do nothing;

insert into sites (brand_id, country_code, base_url, platform, currency, locale,
                   assortment_handles, crawl_delay_ms, notes)
select
  b.id, 'US', 'https://joola.com', 'shopify', 'USD', 'en-US',
  array[
    'pickleball-paddles',
    'professional-pickleball-paddles',
    'pickleball-paddles-performance',
    'recreational-pickleball-paddles',
    'pickleball-paddles-premium',
    'junior-paddles',
    'individual-paddles',
    'joola-3s',
    'gen-1',
    'pro-iv',
    'pro-v',
    'perseus-3s',
    'ben-johns-paddles',
    'outlet-paddles',
    'pickleball-sale'
  ],
  1200,
  'Shopify. Public /collections.json, /products.json and /products/<handle>.js verified open 2026-08-27. No market subpaths (/en-in/ returns 404), so other countries will be separate site rows with their own base_url.'
from brands b where b.slug = 'joola'
on conflict (brand_id, country_code, base_url) do nothing;

-- -----------------------------------------------------------------------------
-- Seed: generations, with sequence so "which version is newer" is orderable.
-- Observed on-site as collections: gen-1, pro-iv, pro-v, joola-3s.
-- -----------------------------------------------------------------------------
insert into generations (brand_id, slug, name, sequence)
select b.id, g.slug, g.name, g.sequence
from brands b
cross join (values
  ('gen-1',  'Gen 1',  1),
  ('gen-2',  'Gen 2',  2),
  ('gen-3',  'Gen 3',  3),
  ('pro-iv', 'Pro IV', 4),
  ('pro-v',  'Pro V',  5),
  ('3s',     '3S',     6)
) as g(slug, name, sequence)
where b.slug = 'joola'
on conflict (brand_id, slug) do nothing;

-- -----------------------------------------------------------------------------
-- Seed: product lines, from the `*-series` tags observed in the live catalogue.
-- The normalize stage will create any line it meets that is not listed here, so
-- this is a head start, not a closed set.
-- -----------------------------------------------------------------------------
insert into product_lines (brand_id, slug, name)
select b.id, l.slug, l.name
from brands b
cross join (values
  ('perseus',  'Perseus'),
  ('hyperion', 'Hyperion'),
  ('scorpeus', 'Scorpeus'),
  ('magnus',   'Magnus'),
  ('vision',   'Vision'),
  ('agassi',   'Agassi'),
  ('graf',     'Graf'),
  ('kosmos',   'Kosmos'),
  ('astro',    'Astro'),
  ('essentials','Essentials')
) as l(slug, name)
where b.slug = 'joola'
on conflict (brand_id, slug) do nothing;

-- -----------------------------------------------------------------------------
-- Seed: endorsing players seen in colourway names
-- ('Blaze Red (Ben Johns)', 'JOOLA Yellow (Anna Bright)', ...).
-- -----------------------------------------------------------------------------
insert into players (brand_id, slug, name)
select b.id, p.slug, p.name
from brands b
cross join (values
  ('ben-johns',          'Ben Johns'),
  ('collin-johns',       'Collin Johns'),
  ('anna-bright',        'Anna Bright'),
  ('tyson-mcguffin',     'Tyson McGuffin'),
  ('simone-jardim',      'Simone Jardim'),
  ('federico-staksrud',  'Federico Staksrud'),
  ('andre-agassi',       'Andre Agassi'),
  ('steffi-graf',        'Steffi Graf'),
  ('hugo-calderano',     'Hugo Calderano')
) as p(slug, name)
where b.slug = 'joola'
on conflict (brand_id, slug) do nothing;

-- >>>>>>>>>>>>>>>>>>>> 20260827000005_vocabularies_and_play_style.sql <<<<<<<<<<<<<<<<<<<<
-- =============================================================================
-- 20260827000005 — the last migration that has to be pasted by hand.
--
-- Two jobs:
--
--   1. Add the play-style axis (power / control / hybrid). Selkirk merchandises
--      it as a first-class dimension with dedicated collections and tags; JOOLA
--      does not use it at all, which is why it defaults to 'unknown'.
--
--   2. Replace every brand-vocabulary CHECK constraint with a reference table.
--
-- Job 2 is the important one. CHECK constraints looked tidy while JOOLA was the
-- only brand, but they hardcode one brand's vocabulary into the schema: the
-- moment a brand ships a shape we have not seen, or a tier word we have not
-- met, the fix is a schema migration — DDL, which cannot be applied over the
-- REST API and therefore needs a human pasting SQL into a dashboard.
--
-- A reference table turns that same change into an INSERT. Inserts go over
-- PostgREST with the service key, which means `npm run sync` can do it. After
-- this migration, onboarding a brand touches no SQL at all.
--
-- Integrity is preserved, not traded away: the columns become foreign keys, so
-- an unknown value is still rejected — it just becomes a row we can add from
-- code rather than a constraint we must redeploy.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Vocabulary reference tables
-- -----------------------------------------------------------------------------
create table if not exists skill_tiers (
  code        text primary key,
  label       text not null,
  sort_order  integer not null default 100,
  notes       text
);

create table if not exists shapes (
  code        text primary key,
  label       text not null,
  sort_order  integer not null default 100,
  notes       text
);

create table if not exists play_styles (
  code        text primary key,
  label       text not null,
  sort_order  integer not null default 100,
  notes       text
);

create table if not exists category_roles (
  code        text primary key,
  label       text not null,
  sort_order  integer not null default 100,
  notes       text
);

-- Current vocabulary. `npm run sync` adds to these as brands introduce words;
-- seeding here only guarantees the foreign keys below can validate today's rows.
insert into skill_tiers (code, label, sort_order) values
  ('pro',          'Pro',           10),
  ('performance',  'Performance',   20),
  ('premium',      'Premium',       30),
  ('recreational', 'Recreational',  40),
  ('junior',       'Junior',        50),
  ('unknown',      'Unknown',      900)
on conflict (code) do nothing;

insert into shapes (code, label, sort_order) values
  ('elongated', 'Elongated',  10),
  ('hybrid',    'Hybrid',     20),
  ('standard',  'Standard',   30),
  ('widebody',  'Widebody',   40),
  ('unknown',   'Unknown',   900)
on conflict (code) do nothing;

insert into play_styles (code, label, sort_order) values
  ('power',   'Power',     10),
  ('control', 'Control',   20),
  ('hybrid',  'Hybrid',    30),
  ('unknown', 'Unknown',  900)
on conflict (code) do nothing;

insert into category_roles (code, label, sort_order) values
  ('sport',      'Sport',        10),
  ('assortment', 'Assortment',   20),
  ('skill_tier', 'Skill tier',   30),
  ('generation', 'Generation',   40),
  ('series',     'Series',       50),
  ('signature',  'Signature',    60),
  ('play_style', 'Play style',   70),
  ('shape',      'Shape',        80),
  ('material',   'Material',     90),
  ('sale',       'Sale',        100),
  ('accessory',  'Accessory',   110),
  ('other',      'Other',       900)
on conflict (code) do nothing;

-- -----------------------------------------------------------------------------
-- 2. play_style on models
--
-- Added before the foreign keys so the new column is covered by them too.
-- -----------------------------------------------------------------------------
alter table models
  add column if not exists play_style text not null default 'unknown';

create index if not exists models_play_style_idx on models(play_style);

-- -----------------------------------------------------------------------------
-- 3. Swap CHECK constraints for foreign keys
--
-- Inline unnamed CHECKs get the name <table>_<column>_check, which is what the
-- drops below target. `if exists` makes this safe whether or not an earlier
-- draft of this migration was already applied.
-- -----------------------------------------------------------------------------
alter table models     drop constraint if exists models_skill_tier_check;
alter table models     drop constraint if exists models_shape_check;
alter table models     drop constraint if exists models_play_style_check;
alter table variants   drop constraint if exists variants_shape_check;
alter table categories drop constraint if exists categories_category_role_check;

-- Any row holding a value outside the seeded vocabulary would block the foreign
-- keys below. There should be none; this repairs rather than aborts if there is.
update models     set skill_tier    = 'unknown' where skill_tier    not in (select code from skill_tiers);
update models     set shape         = 'unknown' where shape         not in (select code from shapes);
update models     set play_style    = 'unknown' where play_style    not in (select code from play_styles);
update variants   set shape         = null      where shape is not null
                                                  and shape not in (select code from shapes);
update categories set category_role = 'other'   where category_role not in (select code from category_roles);

alter table models
  drop constraint if exists models_skill_tier_fkey,
  add constraint models_skill_tier_fkey
    foreign key (skill_tier) references skill_tiers(code) on update cascade;

alter table models
  drop constraint if exists models_shape_fkey,
  add constraint models_shape_fkey
    foreign key (shape) references shapes(code) on update cascade;

alter table models
  drop constraint if exists models_play_style_fkey,
  add constraint models_play_style_fkey
    foreign key (play_style) references play_styles(code) on update cascade;

alter table variants
  drop constraint if exists variants_shape_fkey,
  add constraint variants_shape_fkey
    foreign key (shape) references shapes(code) on update cascade;

alter table categories
  drop constraint if exists categories_category_role_fkey,
  add constraint categories_category_role_fkey
    foreign key (category_role) references category_roles(code) on update cascade;

-- -----------------------------------------------------------------------------
-- 4. Read access to the vocabularies
--
-- RLS is deny-by-default across this schema and the dashboard reads server-side
-- with the service key, so these need no policy to work today. Enabling RLS
-- keeps them consistent with every other table rather than silently readable if
-- an anon key is ever pointed at them.
-- -----------------------------------------------------------------------------
alter table skill_tiers    enable row level security;
alter table shapes         enable row level security;
alter table play_styles    enable row level security;
alter table category_roles enable row level security;

-- =============================================================================
-- 5. Views: surface play_style, weight_grams, shape and brand_slug.
--
-- Rebuilt rather than replaced because CREATE OR REPLACE VIEW cannot insert a
-- column into the middle of a select list. Dropping dependants first keeps the
-- order valid. Views hold no data — this is not a destructive operation, though
-- the SQL editor's guard will ask you to confirm it.
-- =============================================================================
drop view if exists v_active_discounts;
drop view if exists v_model_overview;
drop view if exists v_variant_current;

create view v_variant_current as
select
  v.id                    as variant_id,
  v.sku,
  v.title                 as variant_title,
  v.core_thickness_mm,
  v.colorway,
  v.weight_grams,
  v.shape                 as variant_shape,
  v.attr_confidence,
  pl_player.name          as endorsed_player,

  p.id                    as product_id,
  p.title                 as product_title,
  p.handle,
  p.url                   as product_url,
  p.image_url,
  p.tags,
  p.is_in_assortment,

  m.id                    as model_id,
  m.name                  as model_name,
  m.skill_tier,
  m.play_style,
  m.shape                 as model_shape,
  line.name               as product_line,
  gen.name                as generation,
  gen.sequence            as generation_sequence,

  s.id                    as site_id,
  b.name                  as brand,
  b.slug                  as brand_slug,
  s.country_code,

  snap.observed_at,
  snap.price,
  snap.compare_at_price,
  snap.currency,
  snap.is_on_sale,
  snap.discount_pct,
  snap.is_available,
  snap.inventory_quantity,

  v.is_active
from variants v
join products p        on p.id = v.product_id
join sites s           on s.id = v.site_id
join brands b          on b.id = s.brand_id
left join models m     on m.id = p.model_id
left join product_lines line on line.id = m.product_line_id
left join generations gen    on gen.id = m.generation_id
left join players pl_player  on pl_player.id = v.endorsed_player_id
left join lateral (
  select vs.observed_at, vs.price, vs.compare_at_price, vs.currency,
         vs.is_on_sale, vs.discount_pct, vs.is_available, vs.inventory_quantity
  from variant_snapshots vs
  where vs.variant_id = v.id
  order by vs.observed_at desc
  limit 1
) snap on true;

create view v_model_overview as
select
  m.id                as model_id,
  b.name              as brand,
  b.slug              as brand_slug,
  line.name           as product_line,
  gen.name            as generation,
  gen.sequence        as generation_sequence,
  m.name              as model_name,
  m.skill_tier,
  m.play_style,
  m.shape,
  count(distinct vc.variant_id)                              as sku_count,
  array_agg(distinct vc.core_thickness_mm)
    filter (where vc.core_thickness_mm is not null)          as thicknesses_mm,
  array_agg(distinct vc.colorway)
    filter (where vc.colorway is not null)                   as colorways,
  array_agg(distinct vc.variant_shape)
    filter (where vc.variant_shape is not null
            and vc.variant_shape <> 'unknown')               as shapes,
  array_agg(distinct vc.endorsed_player)
    filter (where vc.endorsed_player is not null)            as endorsed_players,
  min(vc.price)                                              as price_min,
  max(vc.price)                                              as price_max,
  count(*) filter (where vc.is_available)                    as skus_in_stock,
  count(*) filter (where vc.is_on_sale)                      as skus_on_sale,
  max(vc.discount_pct)                                       as best_discount_pct,
  vc.currency,
  vc.country_code
from models m
join brands b on b.id = m.brand_id
left join product_lines line on line.id = m.product_line_id
left join generations gen    on gen.id = m.generation_id
join v_variant_current vc    on vc.model_id = m.id
where vc.is_in_assortment
group by m.id, b.name, b.slug, line.name, gen.name, gen.sequence,
         m.name, m.skill_tier, m.play_style, m.shape, vc.currency, vc.country_code;

create view v_active_discounts as
select
  vc.brand, vc.brand_slug, vc.country_code, vc.product_line, vc.generation,
  vc.model_name, vc.product_title, vc.variant_title, vc.sku,
  vc.core_thickness_mm, vc.colorway,
  vc.price, vc.compare_at_price, vc.discount_pct, vc.currency,
  vc.is_available, vc.product_url, vc.observed_at
from v_variant_current vc
where vc.is_on_sale and vc.is_in_assortment
order by vc.discount_pct desc;

-- The change feed gains brand_slug so the dashboard can filter without a join.
--
-- Dropped first, like the three above. CREATE OR REPLACE VIEW can only append
-- columns to the end of the select list; brand_slug belongs next to brand, and
-- inserting it there is a rename as far as Postgres is concerned:
--   ERROR 42P16: cannot change name of view column "country_code" to "brand_slug"
drop view if exists v_recent_changes;

create view v_recent_changes as
select
  e.id, e.event_type, e.occurred_at, e.old_value, e.new_value,
  e.delta_numeric, e.delta_pct,
  v.sku, v.title as variant_title, v.core_thickness_mm, v.colorway,
  p.title as product_title, p.url as product_url,
  m.name as model_name, m.skill_tier,
  b.name as brand, b.slug as brand_slug, s.country_code
from variant_events e
join variants v on v.id = e.variant_id
join products p on p.id = v.product_id
join sites s    on s.id = e.site_id
join brands b   on b.id = s.brand_id
left join models m on m.id = p.model_id
order by e.occurred_at desc;

-- =============================================================================
-- Deliberately NOT here: the Selkirk brand, site and product lines.
--
-- Those are data, not schema. An earlier draft of this migration seeded them in
-- SQL, which is what made every new brand look like it needed a migration. They
-- now live in src/config/ and are pushed by `npm run sync`, so brand #3 is a
-- TypeScript file and a command — no dashboard, no paste.
-- =============================================================================

-- >>>>>>>>>>>>>>>>>>>> 20260828000001_reviews.sql <<<<<<<<<<<<<<<<<<<<
-- =============================================================================
-- 0006_reviews.sql — customer reviews, brand replies, and their time series
--
-- Three layers, mirroring the rest of the schema:
--
--   reviews                   what a customer wrote      (upserted, carries seen-dates)
--   review_responses          what the brand wrote back  (upserted, the reply chain)
--   product_review_snapshots  what the shelf looked like (append-only, one row per run)
--
-- Why a review needs BOTH an upsert table and a snapshot table:
--
-- A review is not a price. Its text is written once and rarely changes, so
-- re-inserting it every run would multiply one customer's opinion by the number
-- of times we happened to look. But the things *around* it do move — helpful
-- counts climb, the brand replies a week later, and the product's average drifts
-- as new reviews land. So the review itself is upserted on its source id and
-- carries first_seen_at / last_seen_at, while the aggregate that actually moves
-- is snapshotted per run. That is what makes "how did sentiment move over the
-- last six months" a range scan rather than an archaeology project.
--
-- Every brand runs a different review platform (Bazaarvoice / Okendo /
-- Judge.me), so review_platform is carried on the row and the source id is only
-- unique within it. See docs/REVIEWS_RESEARCH.md.
-- =============================================================================

-- Which review platform a storefront runs, and what the adapter needs to reach
-- it (Bazaarvoice client + displayCode, Okendo subscriberId, Judge.me shop
-- domain). Config, not schema — so brand #4 stays a config change.
alter table sites add column if not exists review_platform text;
alter table sites add column if not exists review_config jsonb not null default '{}'::jsonb;

-- Run counters for the reviews stage. finaliseRun() writes the whole RunStats
-- object onto the run row, so every stat needs a column here or the update is
-- rejected and the run never leaves 'running'.
alter table crawl_runs add column if not exists reviews_found integer not null default 0;
alter table crawl_runs add column if not exists reviews_new integer not null default 0;
alter table crawl_runs add column if not exists review_responses_new integer not null default 0;

-- product_technologies was the one scraped table carrying no date at all, so a
-- technology claim appearing on or disappearing from a product was invisible.
-- Brought in line with product_categories, which models the same kind of
-- membership-over-time relationship.
alter table product_technologies add column if not exists first_seen_at timestamptz not null default now();
alter table product_technologies add column if not exists last_seen_at  timestamptz not null default now();
alter table product_technologies add column if not exists is_active     boolean not null default true;

-- =============================================================================
-- reviews — one row per customer review, ever.
-- =============================================================================
create table if not exists reviews (
  id                  uuid primary key default gen_random_uuid(),
  site_id             uuid not null references sites(id) on delete cascade,
  product_id          uuid not null references products(id) on delete cascade,

  -- Provenance. Source ids collide across platforms, so the platform is part
  -- of the natural key rather than an attribute hanging off it.
  review_platform     text not null,                 -- bazaarvoice | okendo | judgeme
  source_review_id    text not null,

  -- Content.
  rating              numeric(3,2),                  -- numeric: Okendo can emit halves
  rating_range        integer not null default 5,
  title               text,
  body                text,
  pros                text,
  cons                text,

  -- Author. Display name only — whatever the storefront already shows in public.
  author_name         text,
  author_id           text,
  author_location     text,

  -- Flags a reader filters on.
  is_verified_buyer   boolean,
  is_recommended      boolean,
  is_incentivized     boolean,
  is_syndicated       boolean,
  -- A star with no words. 84 of JOOLA's first 120 are these; they must count
  -- toward the average but must never surface as an empty card in a text search.
  is_ratings_only     boolean not null default false,

  -- Engagement. Current values, refreshed each run.
  helpful_count       integer not null default 0,
  unhelpful_count     integer not null default 0,
  response_count      integer not null default 0,
  photo_count         integer not null default 0,
  video_count         integer not null default 0,

  -- Which SKU the reviewer actually bought, when the platform says so.
  variant_label       text,
  source_variant_id   text,

  -- Platform-specific structured extras, kept whole rather than flattened:
  -- Bazaarvoice Age / Gender / LengthOfOwnership, secondary ratings, badges.
  -- This is the raw material for the sentiment and complaint analysis that will
  -- sit on top of this table later.
  context_data        jsonb not null default '{}'::jsonb,
  media               jsonb not null default '[]'::jsonb,

  -- === Time ==================================================================
  -- submitted_at is when the CUSTOMER wrote it.
  submitted_at        timestamptz,
  source_updated_at   timestamptz,
  -- first_seen_at / last_seen_at are when WE looked. The gap between
  -- submitted_at and first_seen_at is our own collection lag, and keeping both
  -- is what lets a weekly cadence still plot reviews on the day they were left.
  first_seen_at       timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  first_seen_run_id   uuid references crawl_runs(id) on delete set null,
  last_seen_run_id    uuid references crawl_runs(id) on delete set null,

  language_code       text,

  -- Full-text search vector. Generated and stored so the /reviews search is an
  -- index scan rather than a scan-and-tokenise over every row. Title is weighted
  -- above body so "cracked" in a headline outranks it in a paragraph.
  search_tsv          tsvector generated always as (
                        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                        setweight(to_tsvector('english', coalesce(body,  '')), 'B') ||
                        setweight(to_tsvector('english', coalesce(pros,  '')), 'C') ||
                        setweight(to_tsvector('english', coalesce(cons,  '')), 'C')
                      ) stored,

  unique (site_id, review_platform, source_review_id)
);

create index if not exists reviews_product_idx    on reviews(product_id);
create index if not exists reviews_site_idx       on reviews(site_id);
-- The default sort of the reviews page.
create index if not exists reviews_submitted_idx  on reviews(submitted_at desc nulls last);
create index if not exists reviews_rating_idx     on reviews(rating);
create index if not exists reviews_first_seen_idx on reviews(first_seen_at desc);
create index if not exists reviews_search_idx     on reviews using gin(search_tsv);
-- Trigram index backs the substring fallback for queries full-text stems away —
-- a model number, a part name, a two-letter brand.
create index if not exists reviews_body_trgm_idx  on reviews using gin(body gin_trgm_ops);
-- Partial index: "show me the complaints" is the most expensive common query.
create index if not exists reviews_low_rating_idx
  on reviews(site_id, submitted_at desc) where rating <= 3;

-- =============================================================================
-- review_responses — the reply chain.
--
-- Bazaarvoice returns these as ClientResponses[] with no stable id, Judge.me as
-- an inline reply block, Okendo as a comment. None of them guarantee an id, so
-- the dedupe key is a hash of the response body: replies are edited rarely, and
-- an edited reply is genuinely a new thing to have seen.
-- =============================================================================
create table if not exists review_responses (
  id                  uuid primary key default gen_random_uuid(),
  review_id           uuid not null references reviews(id) on delete cascade,
  site_id             uuid not null references sites(id) on delete cascade,

  source_response_id  text,
  response_hash       text not null,                 -- sha256 of the normalised body

  author_name         text,
  department          text,                          -- 'Team JOOLA'
  response_source     text,                          -- 'mc-api'
  body                text not null,

  responded_at        timestamptz,
  first_seen_at       timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  first_seen_run_id   uuid references crawl_runs(id) on delete set null,

  unique (review_id, response_hash)
);

create index if not exists review_responses_review_idx on review_responses(review_id);
create index if not exists review_responses_site_time_idx
  on review_responses(site_id, responded_at desc);

-- =============================================================================
-- product_review_snapshots — append-only, one row per product per run.
--
-- This is the series that answers the question the feature exists for: how is a
-- product's reception changing over months and years. Deliberately denormalised
-- into star buckets so a distribution chart is one row, not a group-by over
-- every review ever written.
-- =============================================================================
create table if not exists product_review_snapshots (
  id                    bigserial primary key,
  run_id                uuid not null references crawl_runs(id) on delete cascade,
  product_id            uuid not null references products(id) on delete cascade,
  site_id               uuid not null references sites(id) on delete cascade,
  observed_at           timestamptz not null default now(),

  -- What the platform itself claims its total is, when it exposes one. Kept
  -- apart from our own count so a truncated crawl is visible rather than silent.
  reported_total        integer,

  review_count          integer not null default 0,  -- rows we hold for this product
  with_text_count       integer not null default 0,
  ratings_only_count    integer not null default 0,
  average_rating        numeric(4,3),

  rating_1_count        integer not null default 0,
  rating_2_count        integer not null default 0,
  rating_3_count        integer not null default 0,
  rating_4_count        integer not null default 0,
  rating_5_count        integer not null default 0,

  recommended_count     integer not null default 0,
  not_recommended_count integer not null default 0,
  verified_count        integer not null default 0,
  with_response_count   integer not null default 0,

  -- Reviews whose first_seen_run_id is this run: the arrival rate, which leads
  -- the average. A drop to zero on a product that averaged ten a week is worth
  -- knowing well before the average itself moves.
  new_review_count      integer not null default 0,

  unique (run_id, product_id)
);

create index if not exists product_review_snapshots_product_time_idx
  on product_review_snapshots(product_id, observed_at desc);
create index if not exists product_review_snapshots_site_time_idx
  on product_review_snapshots(site_id, observed_at desc);
create index if not exists product_review_snapshots_observed_brin_idx
  on product_review_snapshots using brin(observed_at);

-- =============================================================================
-- Views
-- =============================================================================
drop view if exists v_review_search;
drop view if exists v_product_reviews_current;

-- One row per review, pre-joined to everything the search page filters on, so
-- the UI never fans out joins per row.
create view v_review_search as
select
  r.id                as review_id,
  r.review_platform,
  r.source_review_id,
  r.rating,
  r.rating_range,
  r.title,
  r.body,
  r.pros,
  r.cons,
  r.author_name,
  r.author_location,
  r.is_verified_buyer,
  r.is_recommended,
  r.is_incentivized,
  r.is_ratings_only,
  r.helpful_count,
  r.unhelpful_count,
  r.response_count,
  r.photo_count,
  r.variant_label,
  r.context_data,
  r.media,
  r.submitted_at,
  r.first_seen_at,
  r.last_seen_at,

  p.id                as product_id,
  p.title             as product_title,
  p.handle            as product_handle,
  p.url               as product_url,
  p.image_url         as product_image_url,
  p.is_in_assortment,

  m.id                as model_id,
  m.name              as model_name,
  m.skill_tier,
  m.play_style,
  line.name           as product_line,
  gen.name            as generation,

  s.id                as site_id,
  s.country_code,
  b.name              as brand,
  b.slug              as brand_slug
from reviews r
join products p on p.id = r.product_id
join sites s    on s.id = r.site_id
join brands b   on b.id = s.brand_id
left join models m           on m.id = p.model_id
left join product_lines line on line.id = m.product_line_id
left join generations gen    on gen.id = m.generation_id;

-- Latest review standing per product — the aggregate the catalogue and model
-- pages show next to price.
create view v_product_reviews_current as
select
  p.id                as product_id,
  p.title             as product_title,
  p.handle,
  p.model_id,
  s.id                as site_id,
  b.name              as brand,
  b.slug              as brand_slug,
  snap.observed_at,
  snap.reported_total,
  snap.review_count,
  snap.with_text_count,
  snap.average_rating,
  snap.rating_1_count,
  snap.rating_2_count,
  snap.rating_3_count,
  snap.rating_4_count,
  snap.rating_5_count,
  snap.recommended_count,
  snap.not_recommended_count,
  snap.verified_count,
  snap.with_response_count,
  snap.new_review_count
from products p
join sites s  on s.id = p.site_id
join brands b on b.id = s.brand_id
left join lateral (
  select *
  from product_review_snapshots prs
  where prs.product_id = p.id
  order by prs.observed_at desc
  limit 1
) snap on true;

-- =============================================================================
-- RLS. Same posture as the rest of the schema: service_role writes, anon reads.
-- =============================================================================
alter table reviews                  enable row level security;
alter table review_responses         enable row level security;
alter table product_review_snapshots enable row level security;

drop policy if exists reviews_read                  on reviews;
drop policy if exists review_responses_read         on review_responses;
drop policy if exists product_review_snapshots_read on product_review_snapshots;

create policy reviews_read                  on reviews                  for select using (true);
create policy review_responses_read         on review_responses         for select using (true);
create policy product_review_snapshots_read on product_review_snapshots for select using (true);

-- >>>>>>>>>>>>>>>>>>>> migration ledger <<<<<<<<<<<<<<<<<<<<
create table if not exists schema_migrations (
  version text primary key, name text not null,
  applied_at timestamptz not null default now());

insert into schema_migrations (version, name) values
  ('20260827000001', '20260827000001_core_schema.sql'),
  ('20260827000002', '20260827000002_timeseries.sql'),
  ('20260827000003', '20260827000003_views.sql'),
  ('20260827000004', '20260827000004_rls_and_seed.sql'),
  ('20260827000005', '20260827000005_vocabularies_and_play_style.sql'),
  ('20260828000001', '20260828000001_reviews.sql')
on conflict (version) do nothing;
