import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Concatenates supabase/migrations/*.sql into supabase/schema.sql.
 *
 * schema.sql is what you paste into a fresh project's SQL editor. It was
 * maintained by hand, which meant it silently fell behind whenever a migration
 * was added — the same drift problem the `sync` command solves for brand data.
 *
 * Run: npm run schema
 */

const MIGRATIONS = join(process.cwd(), 'supabase', 'migrations')
const OUT = join(process.cwd(), 'supabase', 'schema.sql')

const files = readdirSync(MIGRATIONS)
  .filter((f) => f.endsWith('.sql'))
  .sort()

if (files.length === 0) throw new Error(`no migrations found in ${MIGRATIONS}`)

const parts: string[] = [
  '-- =============================================================================',
  '-- schema.sql — all migrations concatenated, in order.',
  '--',
  '-- GENERATED by `npm run schema`. Edit the files in supabase/migrations/,',
  '-- not this file.',
  '--',
  '-- Paste into the Supabase SQL editor and run once, on an empty project. The',
  '-- final block stamps schema_migrations so a later `npm run migrate` skips them.',
  '-- =============================================================================',
  '',
]

for (const f of files) {
  parts.push(`-- >>>>>>>>>>>>>>>>>>>> ${f} <<<<<<<<<<<<<<<<<<<<`)
  parts.push(readFileSync(join(MIGRATIONS, f), 'utf8').trimEnd())
  parts.push('')
}

parts.push('-- >>>>>>>>>>>>>>>>>>>> migration ledger <<<<<<<<<<<<<<<<<<<<')
parts.push('create table if not exists schema_migrations (')
parts.push('  version text primary key, name text not null,')
parts.push('  applied_at timestamptz not null default now());')
parts.push('')
parts.push('insert into schema_migrations (version, name) values')
parts.push(
  files
    .map((f) => `  ('${f.slice(0, f.indexOf('_'))}', '${f}')`)
    .join(',\n'),
)
parts.push('on conflict (version) do nothing;')
parts.push('')

const out = parts.join('\n')
writeFileSync(OUT, out, 'utf8')
process.stdout.write(
  `wrote supabase/schema.sql — ${files.length} migrations, ${out.split('\n').length} lines\n`,
)
